### ISSUE TITLE
Failing in MS Edge

### ISSUE THREAD

**Issue by StevenTCramer** [davidwengier/SourceGeneratorPlayground#13]
Uncaught Error: This browser does not support WebAssembly.
    at blazor.webassembly.js:1:42456
    at c (blazor.webassembly.js:1:43072)
    at <anonymous>:1:20
    at blazor.webassembly.js:1:43275
    at new Promise (<anonymous>)
    at Object.start (blazor.webassembly.js:1:37752)
    at blazor.webassembly.js:1:35786
    at blazor.webassembly.js:1:33770
    at Object.next (blazor.webassembly.js:1:33875)
    at i (blazor.webassembly.js:1:32589)

**Comment by davidwengier** [comment]
Which version of edge are you using?

Unfortunately if the browser doesn't support WebAssembly there is nothing I can do about it, because this is a WebAssembly site, but I use Edge all the time and it works fine for me. Maybe there is a setting or permission you can turn on?
